server:
  port: 5150

spring:
  liquibase:
    change-log: classpath:db/migrations/liquibase-changelog.xml
    default-schema: employee
    contexts: production
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gql}
    username: ${SPRING_DATASOURCE_USERNAME:gql}
    password: ${SPRING_DATASOURCE_PASSWORD:gql}
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        default_schema: employee
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false

